FROM apache/airflow:2.6.3-python3.9

USER root

RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    build-essential \
    curl \
    netcat-openbsd \
    gosu \
    && apt-get clean

USER airflow

RUN pip install --no-cache-dir \
    apache-airflow-providers-postgres \
    pandas \
    pyarrow \
    psycopg2-binary \
    sqlalchemy==1.4.54 \
    minio \
    requests \
    dbt-core==1.7.14 \
    dbt-postgres==1.7.14 \
    great-expectations==0.18.8 \
    pytest